---
abstract: 'Gruntmaster 6000 Online Judge -- database interface and tools'
author:
  - 'Marius Gavrilescu <marius@ieval.ro>'
build_requires:
  DBD::SQLite: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Gruntmaster-Data
no_index:
  directory:
    - t
    - inc
requires:
  DBIx::Class::Core: '0'
  DBIx::Class::Schema: '0'
  Date::Parse: '0'
  File::Slurp: '0'
  Getopt::Long: '0'
  IO::Prompter: '0'
  JSON: '0'
  Lingua::EN::Inflect: '0'
  POSIX: '0'
  Sub::Name: '0'
  Term::ANSIColor: '0'
  perl: '5.014000'
resources:
  repository: https://git.ieval.ro/?p=gruntmaster-data.git
version: '5999.000003'
